name: 'GitHub Action for AppCenter Mobile UI testing'
author: 'Tuomo Viljanmaa'
description: 'Wraps the appcenter CLI to enable test commands.'
branding:
  icon: 'package'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'Dockerfile'
